### ISSUE TITLE
DiscordAPI missing perm issue

### ISSUE THREAD

**Issue by MeNixq** [Smaug6739/discord-template#1]
Hi Smaug! I was trying to use this template 

But had some errors i fixed some off them but i have one error that i cant fix 

`DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\Nixq\OrionBot\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Nixq\OrionBot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async ApplicationCommandManager.set (C:\Users\Nixq\OrionBot\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18) {
  method: 'put',
  path: '/applications/878413663998984202/guilds/809702809196560405/commands',
  code: 50001,
  httpStatus: 403,
  requestData: {
    json: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    files: []
  }
}`

**Comment by Smaug6739** [comment]
with what command does this happen? can you send the code?

**Comment by MeNixq** [comment]
it just happens on startup

**Comment by Smaug6739** [comment]
Try to give the bot more permissions. Check that it can send messages and have access to channels

**Comment by MeNixq** [comment]
okay
do you have discord?

**Comment by Smaug6739** [comment]
> Try to give the bot more permissions. Check that it can send messages and have access to channels

Ah and invite the bot with the scope application.commands 
https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links

**Comment by Smaug6739** [comment]
> okay
> do you have discord?

Yes Smaug#6739 on discord

**Comment by Smaug6739** [comment]
The solution is to replace the guild id in ready.ts with the correct one.
